---
title:"Reproducible Research: Peer Assessment 1"
output: 
        html_ document: 
                keep_md: true
---

## Loading and preprocessing the data

Setting global options to turn warnings off
```{r}
knitr::opts_chunk$set(warning=FALSE)
```

Adding data and loading ggplot2 
```{r}
library(ggplot2)
activity <-read.csv("activity.csv")
activity$date <-as.POSIXct(activity$date,"%Y-%m-%d")
weekday <- weekdays(activity$date)
activity <- cbind(activity,weekday)

##Verify dataset is preprocessed correctly
summary(activity)
```

## What is mean total number of steps taken per day? 

```{r}
activity_total_steps <- with(activity, aggregate(steps, by = list(date), FUN = sum, na.rm = TRUE))
names(activity_total_steps) <- c("date", "steps")
hist(activity_total_steps$steps, main = "Total number of steps taken per day", xlab = "Total steps taken per day", col = "darkblue", ylim = c(0,20), breaks = seq(0,25000, by=2500))
```

Mean total number of steps taken per day is `r meansteps`.

```{r}
meansteps <- mean(activity_total_steps$steps)
```

## What is the average daily activity pattern? 

## Imputing missing values

## Are there differences in activity patterns between weekdays and weekends?